version: "3.7"

services:
  database_unit_tests_challenge:
    image: postgres
    container_name: database_unit_tests_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=unit_tests_challenge
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
